### ISSUE TITLE
Why is this not published to npm?

### ISSUE THREAD

**Issue by sukima** [Skalar/ember-keyboard-shortcuts#1]
How come we have to install this via github? Seems a `npm install --save ember-keyboard-shortcuts` would be easier and you can search npmjs.com for it with the ember-addon keyword or via http://www.emberaddons.com/

Please consider publishing to NPM (`npm publish`). Thanks.

**Comment by sukima** [comment]
Per the license:

>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, **publish**, distribute, sublicense, and/or sell copies of the Software
>
>subject to the following conditions: The [MIT] copyright notice and [the LICENSE.md] permission notice shall be included in all copies or substantial portions of the Software.

AFAIK, The above is satisfied even if another author (myself) were to publish to NPM on behalf of the original author (you). I plan to use this inside another ember-cli addon (requiring this node package to be part of the published bundle). Requiring a project through GitHub is a bit sketchy and not a good practice (especially with recent DDOS attacks). A better solution is to publish to NPM.

I have done this on your behalf. Send me your NPM username so I can add you as an owner.

**Comment by trym** [comment]
I was planning to publish to npm once I had added some tests, but became busy with other stuff. Thanks :)

**Comment by trym** [comment]
My npm username is trym

**Comment by sukima** [comment]
Added.
