### ISSUE TITLE
Maintaining the library

### ISSUE THREAD

**Issue by jamesdixon** [Skalar/ember-keyboard-shortcuts#10]
@trym great addon. are you planning on maintaining it going forward? I noticed there are some longstanding PRs and Mousetrap is now at 1.5.3. 

If you don't have the time, I'd be more than happy to help maintain it if you add me as a contributor. If not, I'll probably go ahead and just maintain my own fork.

Thanks!

**Comment by trym** [comment]
For some reason I don't receive pull request notifications. Just merged them. I'll give you access nonetheless :)

**Comment by jamesdixon** [comment]
@trym thanks for the add!
