### ISSUE TITLE
Routing via component

### ISSUE THREAD

**Issue by marineb** [Skalar/ember-keyboard-shortcuts#13]
Hi, 

Is there anyway to re-route within the component instead of via a route? 
What is then the point to add the keyboard shortcuts to the component if we still need to also add the functions in the route? Unless I'm missing something? I don't want to have to repeat my "actions" in each route. I'd like to contain all of this in my component. Is it possible?

Thank you!

**Comment by josemarluedke** [comment]
Closing this. Feel free to reopen if you don't agree with the answer above.
