### ISSUE TITLE
In Ember 2.12+ the bower dependency causes a "bower 1.8.0 is deprecated" warning

### ISSUE THREAD

**Issue by justastefan** [Skalar/ember-keyboard-shortcuts#14]
Using this cool addon causes a "bower 1.8.0 is deprecated" warning in Ember 2.12, since you have to add "bower@1.8.0" in your ember package.json dependency list to fetch all bower stuff.
Could the single bower to "mousetrap": "~1.5.2" be replaced by the NPM equivalent? I didn't investigate beyond checking that there's a package in NPM (see https://www.npmjs.com/package/mousetrap) that does the same.

**Comment by chvonrohr** [comment]
Is this already in work or would you like to have a PR?

**Comment by olivierchatry** [comment]
Done.
