### ISSUE TITLE
Cannot read property 'bind' of undefined in latest 1.0.1 version

### ISSUE THREAD

**Issue by GottfridL** [Skalar/ember-keyboard-shortcuts#19]
I recently tried to upgrade from 0.3.0 to version 1.0.1 to get rid of the event storms that caused me trouble.

However it stopped working when using keyboardShortcuts on a route. I get the error Cannot read property 'bind' of undefined.

It seems as mousetrap is not defined when reaching mousetrap.bind inside the invokeAction method in create-mixin.js. The error is simple to reproduce with the following simple shortcut to an action set:

```
keyboardShortcuts: {
    'esc': 'cancel'
}
```
I can see that mousetrap is not initialized on declaration as it was before. Since my actionObject is global, not scoped and does not have a targetElement it will not get into any of the if statements where mousetrap is set.

**Comment by olivierchatry** [comment]
Can you create a simple sample I can test on ?

**Comment by olivierchatry** [comment]
ad781c2 should fix it

**Comment by olivierchatry** [comment]
@GottfridL can you check so that I can publish the version if it good enough ?

**Comment by GottfridL** [comment]
Sorry for not responding fast.
I have verified that my case now works after this fix (ie version 1.0.2), thank you.

**Comment by rlivsey** [comment]
👍 Can we get a release to NPM of 1.0.2 with this fix?

**Comment by olivierchatry** [comment]
Oops, seems like I did not get any notification. Releasing ASAP.
