### ISSUE TITLE
Don't depend on Bower (deprecated) for fetching the mousetrap repo

### ISSUE THREAD

**Issue by myartsev** [Skalar/ember-keyboard-shortcuts#20]

**Comment by olivierchatry** [comment]
Will take a look tomorrow.

**Comment by olivierchatry** [comment]
Hum, I don't think we are depending on bower to get mousetrap.

**Comment by myartsev** [comment]
```
ember new ember-foo
cd ember-foo
ember install ember-keyboard-shortcuts
```

_npm: Installed ember-keyboard-shortcuts
installing ember-keyboard-shortcuts
  install bower package mousetrap
npm: Installed bower
  cached https://github.com/ccampbell/mousetrap.git#1.5.3
Bower: Installed mousetrap=mousetrap#~1.5.3
Installed addon package._

And mousetrap is fetched to **ember-foo/bower_components/mousetrap/**
Also worth pointing out that there is also an npm mousetrap package as well @ **ember-foo/node_modules/mousetrap/**

**Comment by olivierchatry** [comment]
Trying now. I read the whole thing and did not find any reference of bower.
Will take a deeper look.

**Comment by olivierchatry** [comment]
Never mind found it. I wonder how I missed it :/

**Comment by myartsev** [comment]
No worries =)

**Comment by olivierchatry** [comment]
Done, version is 1.0.3.

**Comment by myartsev** [comment]
Thanks :)
P.S: **.bowerrc** can also be removed

**Comment by olivierchatry** [comment]
Done ! v1.0.5 ( well, f'ed up the version, as always, sorry ).
